sudo: false
dist: trusty
language: rust

rust:
- stable
- beta
- nightly

script:
- rustc --version
#- make install-protobuf
#- cargo install protobuf
- cargo check --all

notifications:
  email:
    on_success: never
    on_failure: never